version: '3.8'

services:
  client-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/client-db
      - JWT_SECRET=your-production-jwt-secret-change-this
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - client-network

  mongodb:
    image: mongo:6.0
    container_name: client-mongodb
    environment:
      - MONGO_INITDB_DATABASE=client-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - client-network

volumes:
  mongodb_data:

networks:
  client-network:
    driver: bridge